-file("/home/oskar/.asdf/installs/erlang/25.3/lib/parsetools-2.4.1/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/lexer.xrl", 27).


-file("/home/oskar/.asdf/installs/erlang/25.3/lib/parsetools-2.4.1/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transition state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/lexer.erl", 308).
yystate() -> 89.

yystate(120, [108|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 9, Tlen);
yystate(120, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(120, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(120, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(120, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(120, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(120, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,120};
yystate(119, [99|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(119, [97|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(119, [98|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(119, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(119, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(119, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(119, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(119, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,119};
yystate(118, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 6, Tlen);
yystate(118, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 6, Tlen);
yystate(118, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 6, Tlen);
yystate(118, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 6, Tlen);
yystate(118, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,118};
yystate(117, [97|Ics], Line, Tlen, _, _) ->
    yystate(101, Ics, Line, Tlen+1, 9, Tlen);
yystate(117, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(117, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(117, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(117, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(117, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,117};
yystate(116, [97|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 9, Tlen);
yystate(116, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(116, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,116};
yystate(115, [101|Ics], Line, Tlen, _, _) ->
    yystate(83, Ics, Line, Tlen+1, 9, Tlen);
yystate(115, [97|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 9, Tlen);
yystate(115, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(115, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(115, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(115, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 100 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(115, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(115, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,115};
yystate(114, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(104, Ics, Line, Tlen+1, Action, Alen);
yystate(114, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,114};
yystate(113, [110|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 9, Tlen);
yystate(113, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(113, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(113, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(113, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(113, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(113, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,113};
yystate(112, [111|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line, Tlen+1, 9, Tlen);
yystate(112, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(112, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,112};
yystate(111, [95|Ics], Line, Tlen, _, _) ->
    yystate(99, Ics, Line, Tlen+1, 2, Tlen);
yystate(111, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 55 ->
    yystate(111, Ics, Line, Tlen+1, 2, Tlen);
yystate(111, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,111};
yystate(110, [101|Ics], Line, Tlen, _, _) ->
    yystate(116, Ics, Line, Tlen+1, 9, Tlen);
yystate(110, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(110, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,110};
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(109, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,109};
yystate(108, [61|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 7, Tlen);
yystate(108, [42|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 7, Tlen);
yystate(108, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,108};
yystate(107, [108|Ics], Line, Tlen, _, _) ->
    yystate(103, Ics, Line, Tlen+1, 9, Tlen);
yystate(107, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(107, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,107};
yystate(106, [97|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 9, Tlen);
yystate(106, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(106, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,106};
yystate(105, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(104, [95|Ics], Line, Tlen, _, _) ->
    yystate(114, Ics, Line, Tlen+1, 4, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(104, Ics, Line, Tlen+1, 4, Tlen);
yystate(104, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,104};
yystate(103, [108|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 9, Tlen);
yystate(103, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(103, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(103, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(103, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(103, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(103, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,103};
yystate(102, [100|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(102, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(102, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,102};
yystate(101, [109|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 9, Tlen);
yystate(101, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(101, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,101};
yystate(100, [115|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 9, Tlen);
yystate(100, [105|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 9, Tlen);
yystate(100, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 114 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(100, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,100};
yystate(99, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 55 ->
    yystate(111, Ics, Line, Tlen+1, Action, Alen);
yystate(99, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,99};
yystate(98, [101|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 4, Tlen);
yystate(98, [95|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 4, Tlen);
yystate(98, [69|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 4, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(98, Ics, Line, Tlen+1, 4, Tlen);
yystate(98, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,98};
yystate(97, [105|Ics], Line, Tlen, _, _) ->
    yystate(113, Ics, Line, Tlen+1, 9, Tlen);
yystate(97, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(97, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,97};
yystate(96, [110|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 9, Tlen);
yystate(96, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(96, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,96};
yystate(95, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(95, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,95};
yystate(94, [102|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(94, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(94, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,94};
yystate(93, [97|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 9, Tlen);
yystate(93, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(93, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,93};
yystate(92, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,92};
yystate(91, [101|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 9, Tlen);
yystate(91, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(91, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,91};
yystate(90, [108|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 9, Tlen);
yystate(90, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(90, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,90};
yystate(89, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [122|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [121|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [120|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [119|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(115, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [113|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(117, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [106|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [107|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(120, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [70|Ics], Line, Tlen, Action, Alen) ->
    yystate(106, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(108, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(105, Ics, Line+1, Tlen+1, Action, Alen);
yystate(89, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 69 ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 77 ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [C|Ics], Line, Tlen, Action, Alen) when C >= 79, C =< 83 ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [C|Ics], Line, Tlen, Action, Alen) when C >= 85, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(89, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,89};
yystate(88, [107|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(88, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 106 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 108, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(88, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,88};
yystate(87, [110|Ics], Line, Tlen, _, _) ->
    yystate(119, Ics, Line, Tlen+1, 9, Tlen);
yystate(87, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(87, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,87};
yystate(86, [39|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 11, Tlen);
yystate(86, [34|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 11, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(9, Ics, Line, Tlen+1, 11, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(9, Ics, Line, Tlen+1, 11, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 38 ->
    yystate(9, Ics, Line, Tlen+1, 11, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 40 ->
    yystate(9, Ics, Line, Tlen+1, 11, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,86};
yystate(85, [61|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 7, Tlen);
yystate(85, [60|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 7, Tlen);
yystate(85, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,85};
yystate(84, [98|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 9, Tlen);
yystate(84, [97|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(84, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(84, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,84};
yystate(83, [116|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 9, Tlen);
yystate(83, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,83};
yystate(82, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(98, Ics, Line, Tlen+1, Action, Alen);
yystate(82, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,82};
yystate(81, [117|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 9, Tlen);
yystate(81, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,81};
yystate(80, [105|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, [104|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,80};
yystate(79, [114|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 9, Tlen);
yystate(79, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(79, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,79};
yystate(78, [114|Ics], Line, Tlen, _, _) ->
    yystate(110, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,78};
yystate(77, [95|Ics], Line, Tlen, _, _) ->
    yystate(109, Ics, Line, Tlen+1, 5, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 5, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,77};
yystate(76, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(114, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(104, Ics, Line, Tlen+1, Action, Alen);
yystate(76, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,76};
yystate(75, [97|Ics], Line, Tlen, _, _) ->
    yystate(107, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,75};
yystate(74, [114|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 9, Tlen);
yystate(74, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,74};
yystate(73, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(72, [116|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,72};
yystate(71, [122|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(71, [121|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(71, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 120 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,71};
yystate(70, [108|Ics], Line, Tlen, _, _) ->
    yystate(102, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,70};
yystate(69, [98|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, [97|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,69};
yystate(68, [111|Ics], Line, Tlen, _, _) ->
    yystate(96, Ics, Line, Tlen+1, 9, Tlen);
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,68};
yystate(67, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(99, Ics, Line, Tlen+1, Action, Alen);
yystate(67, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 55 ->
    yystate(111, Ics, Line, Tlen+1, Action, Alen);
yystate(67, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,67};
yystate(66, [111|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 9, Tlen);
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,66};
yystate(65, [116|Ics], Line, Tlen, _, _) ->
    yystate(97, Ics, Line, Tlen+1, 9, Tlen);
yystate(65, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,65};
yystate(64, [62|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [61|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,64};
yystate(63, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(63, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,63};
yystate(62, [101|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,62};
yystate(61, [99|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 9, Tlen);
yystate(61, [97|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(61, [98|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,61};
yystate(60, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(114, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(104, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [117|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,59};
yystate(58, [115|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 9, Tlen);
yystate(58, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,58};
yystate(57, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(56, [119|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [115|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [110|Ics], Line, Tlen, _, _) ->
    yystate(102, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 114 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 118 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 120, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,56};
yystate(55, [122|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 6, Tlen);
yystate(55, [121|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 6, Tlen);
yystate(55, [115|Ics], Line, Tlen, _, _) ->
    yystate(91, Ics, Line, Tlen+1, 6, Tlen);
yystate(55, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 6, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 6, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 6, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(92, Ics, Line, Tlen+1, 6, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 120 ->
    yystate(92, Ics, Line, Tlen+1, 6, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,55};
yystate(54, [101|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 9, Tlen);
yystate(54, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,54};
yystate(53, [61|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 8, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,53};
yystate(52, [108|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,52};
yystate(51, [110|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,51};
yystate(50, [101|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [69|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [46|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,50};
yystate(49, [101|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,49};
yystate(48, [116|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,48};
yystate(47, [95|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, [48|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, [49|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, [44|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,47};
yystate(46, [115|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,46};
yystate(45, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, [120|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [111|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [101|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [98|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [95|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [88|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [79|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [69|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [66|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [46|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,44};
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 1, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,43};
yystate(42, [111|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 9, Tlen);
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,42};
yystate(41, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,41};
yystate(40, [112|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,40};
yystate(39, [121|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [122|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [120|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [108|Ics], Line, Tlen, _, _) ->
    yystate(100, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 119 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,39};
yystate(38, [105|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 9, Tlen);
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,38};
yystate(37, [100|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,37};
yystate(36, [105|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,36};
yystate(35, [114|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,35};
yystate(34, [116|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, [110|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 115 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,34};
yystate(33, [110|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,33};
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 4, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(98, Ics, Line, Tlen+1, 4, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,32};
yystate(31, [108|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 9, Tlen);
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,31};
yystate(30, [108|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [102|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 107 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,30};
yystate(29, [111|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 9, Tlen);
yystate(29, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,29};
yystate(28, [114|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [112|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [113|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [111|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [105|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 110 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,28};
yystate(27, [114|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,27};
yystate(26, [112|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 9, Tlen);
yystate(26, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,26};
yystate(25, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(24, [97|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 9, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,24};
yystate(23, [99|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, [97|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, [98|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,23};
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(22, Ics, Line, Tlen+1, 10, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(22, Ics, Line, Tlen+1, 10, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,22};
yystate(21, [97|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(21, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,21};
yystate(20, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(20, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,20};
yystate(19, [109|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,19};
yystate(18, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,18};
yystate(17, [97|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,17};
yystate(16, [104|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,16};
yystate(15, [61|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, [47|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,15};
yystate(14, [115|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,14};
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, [114|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,12};
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(11, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,11};
yystate(10, [115|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(10, [110|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(10, [109|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 9, Tlen);
yystate(10, [102|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(10, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 108 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 114 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,10};
yystate(9, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 38 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, [101|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 9, Tlen);
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,8};
yystate(7, [105|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 9, Tlen);
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,7};
yystate(6, [61|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,6};
yystate(5, [62|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, [61|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,5};
yystate(4, [110|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,4};
yystate(3, [111|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,3};
yystate(2, [108|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 9, Tlen);
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,2};
yystate(1, [111|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [109|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [110|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [108|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,1};
yystate(0, [105|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 9, Tlen);
yystate(0, [95|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("src/lexer.xrl", 1).
yyaction_0(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, TokenChars } } .

-compile({inline,yyaction_1/2}).
-file("src/lexer.xrl", 2).
yyaction_1(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, TokenChars } } .

-compile({inline,yyaction_2/2}).
-file("src/lexer.xrl", 3).
yyaction_2(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, TokenChars } } .

-compile({inline,yyaction_3/2}).
-file("src/lexer.xrl", 4).
yyaction_3(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, TokenChars } } .

-compile({inline,yyaction_4/2}).
-file("src/lexer.xrl", 6).
yyaction_4(TokenChars, TokenLine) ->
     { token, { float, TokenLine, TokenChars } } .

-compile({inline,yyaction_5/2}).
-file("src/lexer.xrl", 7).
yyaction_5(TokenChars, TokenLine) ->
     { token, { float, TokenLine, TokenChars } } .

-compile({inline,yyaction_6/2}).
-file("src/lexer.xrl", 9).
yyaction_6(TokenChars, TokenLine) ->
     { token, { keyword, TokenLine, TokenChars } } .

-compile({inline,yyaction_7/2}).
-file("src/lexer.xrl", 11).
yyaction_7(TokenChars, TokenLine) ->
     { token, { operator, TokenLine, TokenChars } } .

-compile({inline,yyaction_8/2}).
-file("src/lexer.xrl", 13).
yyaction_8(TokenChars, TokenLine) ->
     { token, { delimiter, TokenLine, TokenChars } } .

-compile({inline,yyaction_9/2}).
-file("src/lexer.xrl", 15).
yyaction_9(TokenChars, TokenLine) ->
     { token, { identifier, TokenLine, TokenChars } } .

-compile({inline,yyaction_10/2}).
-file("src/lexer.xrl", 17).
yyaction_10(TokenChars, TokenLine) ->
     { token, { comment, TokenLine, TokenChars } } .

-compile({inline,yyaction_11/2}).
-file("src/lexer.xrl", 19).
yyaction_11(TokenChars, TokenLine) ->
     { token, { string, TokenLine, TokenChars } } .

-compile({inline,yyaction_12/2}).
-file("src/lexer.xrl", 21).
yyaction_12(TokenChars, TokenLine) ->
     { token, { space, TokenLine, TokenChars } } .

-compile({inline,yyaction_13/2}).
-file("src/lexer.xrl", 23).
yyaction_13(TokenChars, TokenLine) ->
     { token, { endline, TokenLine, TokenChars } } .

-file("/home/oskar/.asdf/installs/erlang/25.3/lib/parsetools-2.4.1/include/leexinc.hrl", 313).
